### ISSUE TITLE
Monaco actions didn't works with keybinding service override

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#244] opened 2023-11-14 12:46 UTC
Hi Team!

I have a lot of custom actions for monaco-editor, they all registered after initialisation process via `createConfiguredEditor` call.
And after that al actions didn't works, just ignoring by editor. What i do wrong?

**Comment by BusinessDuck** [comment] 2023-11-14 12:47
init services looks like this:

```typescript
await monacoLsp.initServices({
	userServices: {
		...modelService.default(),
		...keybindingService.default(),
		...configurationService.default(workspaceUri),
	},
});
```

**Comment by CGNonofr** [comment] 2023-11-14 12:55
can you provide a minimal reproduction code ?

**Comment by CGNonofr** [comment] 2023-11-14 13:26
isn't the demo here enough?

**Comment by BusinessDuck** [comment] 2023-11-14 17:17
```
import getKeybindingsServiceOverride, { initUserKeybindings } from '@codingame/monaco-vscode-keybindings-service-override'
```

<img width="945" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/10143411/c97b33f7-4555-4eee-b148-706ce5287ede">

I am looking at the demo, and didn't see `initUserKeybindings` method in published npm of monaco-vscode-keybindings-service-override

**Comment by BusinessDuck** [comment] 2023-11-14 17:19
I am using `editor.addAction` to register custom actions, and i see my actions in command palette and context menu, but it isnt called by keyboard shorcuts.

**Comment by CGNonofr** [comment] 2023-11-14 17:19
`initUserKeybindings` is a brand new method that should be available in the very last version

**Comment by BusinessDuck** [comment] 2023-11-14 17:25
But why it didnt works out of the box? I mean via `editor.addAction`

**Comment by CGNonofr** [comment] 2023-11-14 18:14
It seems to be a regression, the fix is in https://github.com/CodinGame/monaco-vscode-api/pull/246

**Closed** 2023-11-14 18:41 UTC

**Comment by CGNonofr** [comment] 2023-11-15 08:51
Do you confirm the fix?

**Comment by BusinessDuck** [comment] 2023-11-15 12:10
Not able to build project, packages issues, i am waiting until language client will be released, i let you know

**Comment by kaisalmen** [comment] 2023-11-15 12:32
> Not able to build project, packages issues, i am waiting until language client will be released, i let you know

7.0.2 is available

**Comment by BusinessDuck** [comment] 2023-11-16 09:56
Thanks for the notification about release. Looks much better, working well
